### ISSUE TITLE
Brew & Flowdroid not Compiling; referenced soot release Repository no longer active

### ISSUE THREAD

**Issue by CalixBarrus** [amordahl/RethinkingAndroid_ISSTA2021#1]
Hi there, I'm trying to follow your instructions to setup you replication package, but I've run into a few issues. 

BREW and Flowdroid do not compile, because some of their dependencies in their pom.xml use a repository 
https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-release/ 
or 
https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/. 

It seems that this subdomain is no longer active. Do you know if anyone is hosting old soot artifacts/snapshots?

**Comment by amordahl** [comment]
Hi Calix,

Unfortunately, I can't seem to find anywhere hosting these old Soot versions. It seems Soot moved from hosting their own repos at the Paderborn University domain to hosting versions on Maven Central, which doesn't have anything older than 4.1.0. I raised an issue to double check (https://github.com/soot-oss/soot/issues/2090), but in the meantime I have two suggestions:

(1) If working with the exact environment we used is paramount, I suggest using the virtual machine we host on Zenodo.
(2) If some difference is acceptable, I think upgrading Soot should be okay? I asked in my issue whether Soot 4.x is backward compatible with Soot 3.x. If not, I will try to update the artifact to have the Soot 3.0.0 dependency locally instead of needing to pull it from online.

It's good to have someone else interested in this work! This was one of the first projects I worked on as a Ph.D. student, and I would definitely structure it much differently if I had the knowledge I have now. If I can help in any way, please feel free to raise more issues or reach out to me directly.

Austin

**Comment by CalixBarrus** [comment]
Hi Austin, 
Thanks for your response. I was able to get your VM running, and by pulling the relevant JARs out of the Maven repository, I was able to manually install all the missing JARs and get the old version of Flowdroid to compile. Including the VM as a part of your artifact package was very handy.
